spring:
 application:
  name: Config-default
eureka:
 client:
  fetchRegistry = true
  registerWithEureka = true
  instance:
   preferIpAddress = true
   prefer-ip-address = true
  serviceUrl:
   defaultZone  = http://localhost:8761/eureka/
